In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('Data.csv',encoding='unicode_escape')

In [3]:
df.head(2)

,end_year,citylng,citylat,intensity,sector,topic,insight,swot,url,region,...,impact,added,published,city,country,relevance,pestle,source,title,likelihood
0,2018,NaN,NaN,12,Information Technology,artificial intelligence,What's next for Health IT - Trends for 2018,NaN,http://www.infosysblogs.com/healthcare/2017/06...,NaN,...,NaN,"June, 26 2018 07:28:39","June, 26 2018 00:00:00",NaN,NaN,3,Technological,infosysblogs,Adoption of AI diagnostics is expected to furt...,4
1,2020,NaN,NaN,16,NaN,pharmaceutical,The 8 Healthcare Trends that will impact your ...,NaN,http://www.jhconline.com/the-8-healthcare-tren...,NaN,...,3.0,"June, 26 2018 05:53:45","June, 26 2018 00:00:00",NaN,NaN,4,Healthcare,NaN,The Specialty Pharma market was $274 b in 2010...,4

In [4]:
df.columns

Index(['end_year', 'citylng', 'citylat', 'intensity', 'sector', 'topic',
       'insight', 'swot', 'url', 'region', 'start_year', 'impact', 'added',
       'published', 'city', 'country', 'relevance', 'pestle', 'source',
       'title', 'likelihood'],
      dtype='object')

In [5]:
df.isnull().count

<bound method DataFrame.count of      end_year  citylng  citylat  intensity  sector  topic  insight   swot  \
0       False     True     True      False   False  False    False   True
1       False     True     True      False    True  False    False   True
2       False     True     True      False   False  False    False   True
3       False     True     True      False   False  False    False   True
4       False     True     True      False    True  False    False   True
..        ...      ...      ...        ...     ...    ...      ...    ...
995     False     True     True      False   False  False    False   True
996     False     True     True      False    True   True    False   True
997     False     True     True      False   False  False    False  False
998     False     True     True      False   False  False    False   True
999     False     True     True      False    True  False    False   True

       url  region  ...  impact  added  published  city  country  relevance  \
0    False    True  ...    True  False      False  True     True      False
1    False    True  ...   False  False      False  True     True      False
2    False   False  ...    True  False      False  True     True      False
3    False   False  ...    True  False      False  True     True      False
4    False    True  ...    True  False      False  True     True      False
..     ...     ...  ...     ...    ...        ...   ...      ...        ...
995  False    True  ...    True  False      False  True     True      False
996  False   False  ...   False  False      False  True     True      False
997  False   False  ...   False  False      False  True    False      False
998  False    True  ...    True  False      False  True     True      False
999  False    True  ...    True  False      False  True     True      False

     pestle  source  title  likelihood
0     False   False  False       False
1     False    True  False       False
2     False   False  False       False
3     False   False  False       False
4     False   False  False       False
..      ...     ...    ...         ...
995   False   False  False       False
996    True   False  False       False
997   False   False  False       False
998   False   False  False       False
999   False    True  False       False

[1000 rows x 21 columns]>

In [6]:
df.dtypes

end_year        int64
citylng       float64
citylat       float64
intensity       int64
sector         object
topic          object
insight        object
swot           object
url            object
region         object
start_year    float64
impact        float64
added          object
published      object
city           object
country        object
relevance       int64
pestle         object
source         object
title          object
likelihood      int64
dtype: object

In [7]:
Cd1=df.drop(columns=['citylng','citylat','swot','start_year','country'],axis=1,inplace=True)

In [8]:
Cd1

#### Zero means no nan values or no  null values

In [9]:
df.isnull().sum()

end_year        0
intensity       0
sector        290
topic         158
insight         0
url             0
region        469
impact        741
added           0
published       0
city          986
relevance       0
pestle        159
source         43
title           0
likelihood      0
dtype: int64

In [10]:
df

,end_year,intensity,sector,topic,insight,url,region,impact,added,published,city,relevance,pestle,source,title,likelihood
0,2018,12,Information Technology,artificial intelligence,What's next for Health IT - Trends for 2018,http://www.infosysblogs.com/healthcare/2017/06...,NaN,NaN,"June, 26 2018 07:28:39","June, 26 2018 00:00:00",NaN,3,Technological,infosysblogs,Adoption of AI diagnostics is expected to furt...,4
1,2020,16,NaN,pharmaceutical,The 8 Healthcare Trends that will impact your ...,http://www.jhconline.com/the-8-healthcare-tren...,NaN,3.0,"June, 26 2018 05:53:45","June, 26 2018 00:00:00",NaN,4,Healthcare,NaN,The Specialty Pharma market was $274 b in 2010...,4
2,2024,20,Pharmaceuticals,drug,Market share of top 20 companies for orphan dr...,https://www.statista.com/statistics/373373/top...,World,NaN,"June, 26 2018 03:53:23","June, 26 2018 00:00:00",NaN,5,Healthcare,Statista Infographics,"In 2017, Roche's orphan drugs market share acc...",4
3,2019,16,Information Technology,data,New NASA mission to detect plant water use fro...,https://climate.nasa.gov/news/2752/new-nasa-mi...,World,NaN,"June, 26 2018 06:50:48","June, 26 2018 00:00:00",NaN,4,Technological,Climate Change: Vital Signs of the Planet,"Over the next year, ECOSTRESS will use the spa...",4
4,2020,12,NaN,organization,CylanceÂ® Extends AI-Driven Security to Hybrid ...,http://www.cybersecuritytrend.com/news/2018/06...,NaN,NaN,"June, 26 2018 02:59:51","June, 26 2018 00:00:00",NaN,3,Organization,Cybersecurity Trend,90 percent of organizations will adopt hybrid ...,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2022,12,Energy,research,New solar industry initiatives could open busi...,https://www.utilitydive.com/news/new-solar-ind...,NaN,NaN,"June, 10 2018 12:02:45","June, 07 2018 00:00:00",NaN,3,Social,Utility Dive,GTM Research expects total solar capacity grow...,4
996,2022,60,NaN,NaN,10 Predictions for the Global Orthopedic Devic...,https://www.beckersspine.com/orthopedic-a-spin...,Asia,3.0,"June, 07 2018 02:33:34","June, 07 2018 00:00:00",NaN,5,NaN,McKnights,Among spinal implants and bone growth substitu...,4
997,2020,72,Healthcare,income,IBEF Presentataion,https://www.ibef.org/download/FMCG-June-2018.pdf,Southern Asia,3.0,"June, 19 2018 07:04:10","June, 07 2018 00:00:00",NaN,6,Social,IBEF,Favourable demographics and rise in income lev...,4
998,2020,8,Financial services,retail,"Conference Day One: Tuesday, 19th June 2018",https://openbanking-summit.iqpc.com.au/agenda/...,NaN,NaN,"June, 07 2018 06:21:13","June, 07 2018 00:00:00",NaN,4,Economic,Open Banking Summit,"As seen in Europe, PISPs could account for up ...",2
999,2020,12,NaN,child,"No title could be extracted, please add manually",https://www.childrenscommissioner.gov.uk/wp-co...,NaN,NaN,"June, 18 2018 02:09:06","June, 07 2018 00:00:00",NaN,3,Economic,NaN,UK spending per child is expected to fall by a...,4

In [11]:
df['sector'].unique()

array(['Information Technology', nan, 'Pharmaceuticals', 'Healthcare',
       'Automotive', 'Energy', 'Manufacturing', 'Media & entertainment',
       'Environment', 'Government', 'Tourism & hospitality',
       'Financial services', 'Education', 'Transport', 'Retail',
       'Aerospace & defence', 'Food & agriculture', 'Support services',
       'Construction', 'Security', 'Science', 'Telecoms', 'Water',
       'Mining'], dtype=object)

In [12]:
df.drop(columns=['url','city','title','source'], axis=1, inplace=True)

In [13]:
df

,end_year,intensity,sector,topic,insight,region,impact,added,published,relevance,pestle,likelihood
0,2018,12,Information Technology,artificial intelligence,What's next for Health IT - Trends for 2018,NaN,NaN,"June, 26 2018 07:28:39","June, 26 2018 00:00:00",3,Technological,4
1,2020,16,NaN,pharmaceutical,The 8 Healthcare Trends that will impact your ...,NaN,3.0,"June, 26 2018 05:53:45","June, 26 2018 00:00:00",4,Healthcare,4
2,2024,20,Pharmaceuticals,drug,Market share of top 20 companies for orphan dr...,World,NaN,"June, 26 2018 03:53:23","June, 26 2018 00:00:00",5,Healthcare,4
3,2019,16,Information Technology,data,New NASA mission to detect plant water use fro...,World,NaN,"June, 26 2018 06:50:48","June, 26 2018 00:00:00",4,Technological,4
4,2020,12,NaN,organization,CylanceÂ® Extends AI-Driven Security to Hybrid ...,NaN,NaN,"June, 26 2018 02:59:51","June, 26 2018 00:00:00",3,Organization,4
...,...,...,...,...,...,...,...,...,...,...,...,...
995,2022,12,Energy,research,New solar industry initiatives could open busi...,NaN,NaN,"June, 10 2018 12:02:45","June, 07 2018 00:00:00",3,Social,4
996,2022,60,NaN,NaN,10 Predictions for the Global Orthopedic Devic...,Asia,3.0,"June, 07 2018 02:33:34","June, 07 2018 00:00:00",5,NaN,4
997,2020,72,Healthcare,income,IBEF Presentataion,Southern Asia,3.0,"June, 19 2018 07:04:10","June, 07 2018 00:00:00",6,Social,4
998,2020,8,Financial services,retail,"Conference Day One: Tuesday, 19th June 2018",NaN,NaN,"June, 07 2018 06:21:13","June, 07 2018 00:00:00",4,Economic,2
999,2020,12,NaN,child,"No title could be extracted, please add manually",NaN,NaN,"June, 18 2018 02:09:06","June, 07 2018 00:00:00",3,Economic,4

In [14]:
df['topic']=df['topic'].fillna(df['topic'].mode()[0])

In [15]:
df['region']=df['region'].fillna(df['region'].mode()[0])

In [16]:
df['impact']=df['impact'].fillna(df['impact'].mode()[0])

In [17]:
df['pestle']=df['pestle'].fillna(df['pestle'].mode()[0])

In [18]:
df

,end_year,intensity,sector,topic,insight,region,impact,added,published,relevance,pestle,likelihood
0,2018,12,Information Technology,artificial intelligence,What's next for Health IT - Trends for 2018,World,3.0,"June, 26 2018 07:28:39","June, 26 2018 00:00:00",3,Technological,4
1,2020,16,NaN,pharmaceutical,The 8 Healthcare Trends that will impact your ...,World,3.0,"June, 26 2018 05:53:45","June, 26 2018 00:00:00",4,Healthcare,4
2,2024,20,Pharmaceuticals,drug,Market share of top 20 companies for orphan dr...,World,3.0,"June, 26 2018 03:53:23","June, 26 2018 00:00:00",5,Healthcare,4
3,2019,16,Information Technology,data,New NASA mission to detect plant water use fro...,World,3.0,"June, 26 2018 06:50:48","June, 26 2018 00:00:00",4,Technological,4
4,2020,12,NaN,organization,CylanceÂ® Extends AI-Driven Security to Hybrid ...,World,3.0,"June, 26 2018 02:59:51","June, 26 2018 00:00:00",3,Organization,4
...,...,...,...,...,...,...,...,...,...,...,...,...
995,2022,12,Energy,research,New solar industry initiatives could open busi...,World,3.0,"June, 10 2018 12:02:45","June, 07 2018 00:00:00",3,Social,4
996,2022,60,NaN,economy,10 Predictions for the Global Orthopedic Devic...,Asia,3.0,"June, 07 2018 02:33:34","June, 07 2018 00:00:00",5,Economic,4
997,2020,72,Healthcare,income,IBEF Presentataion,Southern Asia,3.0,"June, 19 2018 07:04:10","June, 07 2018 00:00:00",6,Social,4
998,2020,8,Financial services,retail,"Conference Day One: Tuesday, 19th June 2018",World,3.0,"June, 07 2018 06:21:13","June, 07 2018 00:00:00",4,Economic,2
999,2020,12,NaN,child,"No title could be extracted, please add manually",World,3.0,"June, 18 2018 02:09:06","June, 07 2018 00:00:00",3,Economic,4

In [19]:
df.isnull().sum()

end_year        0
intensity       0
sector        290
topic           0
insight         0
region          0
impact          0
added           0
published       0
relevance       0
pestle          0
likelihood      0
dtype: int64

In [20]:
df.describe()

          end_year    intensity       impact    relevance   likelihood
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000
mean   2025.694000    24.481000     2.969000     4.087000     3.615000
std       8.804992    21.567401     0.316448     1.000216     0.706593
min    2018.000000     3.000000     2.000000     3.000000     1.000000
25%    2020.000000    12.000000     3.000000     3.000000     3.000000
50%    2023.000000    16.000000     3.000000     4.000000     4.000000
75%    2028.000000    30.000000     3.000000     5.000000     4.000000
max    2066.000000   112.000000     4.000000     7.000000     4.000000

In [21]:
file_name = 'cleandata.xlsx'
 
# saving the excel
df.to_excel(file_name)
print('DataFrame is written to Excel File successfully.')

ModuleNotFoundError: No module named 'openpyxl'